# Generated by Django 2.2.13 on 2020-07-02 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('tel', models.CharField(blank=True, max_length=40, verbose_name='Telephone')),
                ('url', models.URLField(blank=True, verbose_name='Web site')),
                ('email', models.EmailField(max_length=254, verbose_name='DSI Email')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Contact')),
                ('contact_tel', models.CharField(blank=True, max_length=100, verbose_name="Contact's tel")),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('charged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charged_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
