# Generated by Django 2.2.12 on 2020-05-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='m', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telephone'),
        ),
    ]
