# Generated by Django 2.2.13 on 2020-07-03 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='charged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charged_clients', to=settings.AUTH_USER_MODEL, verbose_name='Resposable'),
        ),
    ]
