# Generated by Django 2.2.12 on 2020-05-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='client',
            name='signed',
            field=models.DateField(blank=True, null=True, verbose_name='Contract signed on'),
        ),
    ]
