# Generated by Django 2.2.12 on 2020-06-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200523_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='client',
            name='signed',
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_tel',
            field=models.CharField(blank=True, max_length=100, verbose_name="Contact's tel"),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='DSI Email'),
        ),
    ]
