# Generated by Django 2.2.12 on 2020-06-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Display Name'),
        ),
    ]
