# Generated by Django 2.2.12 on 2020-06-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
