# Generated by Django 2.2.12 on 2020-06-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200604_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telephone'),
        ),
    ]
