# Generated by Django 3.0.5 on 2020-05-02 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('titre', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('priorite', models.CharField(choices=[('F', 'Faible'), ('M', 'Moyenne'), ('H', 'Houte'), ('U', 'Urgent')], default='F', max_length=1)),
                ('status', models.CharField(choices=[('EA', 'En attente'), ('RS', 'Resolu'), ('OV', 'Ouvert'), ('FR', 'Ferme'), ('RF', 'Refuse'), ('AN', 'Annule'), ('RP', 'Reponde'), ('DS', 'Desactive')], default='OV', max_length=2)),
                ('categorie', models.CharField(choices=[('RES', 'Reseau'), ('MAT', 'Materiel'), ('lOG', 'Logiciel'), ('AUT', 'Autre')], default='AUT', max_length=3)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reponce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponces', to='solutions.Ticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
