# Generated by Django 2.2.12 on 2020-05-21 15:22

from django.db import migrations, models
import solutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=solutions.models.Question.content_file_name),
        ),
    ]
