# Generated by Django 2.2.12 on 2020-06-04 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import solutions.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='charged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charged_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='ref',
            field=models.CharField(default=solutions.models.Question.ref, editable=False, max_length=100, unique=True),
        ),
    ]
