# Generated by Django 2.2.13 on 2020-07-03 15:17

from django.db import migrations, models
import solutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='priorite_intern',
            field=models.CharField(blank=True, choices=[('F', 'Low'), ('M', 'Medium'), ('H', 'Height'), ('U', 'Urgent'), ('B', 'Bloquant')], default='F', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='ref',
            field=models.PositiveIntegerField(default=solutions.models.Question.ref, verbose_name='Reference'),
        ),
    ]
