# Generated by Django 2.2.12 on 2020-06-20 09:39

from django.db import migrations, models
import solutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ref',
            field=models.PositiveIntegerField(default=solutions.models.Question.ref, verbose_name='Reference'),
        ),
    ]
