# Generated by Django 3.0.5 on 2020-05-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_auto_20200502_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
