# Generated by Django 2.2.12 on 2020-06-05 15:14

from django.db import migrations, models
import solutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_auto_20200604_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ref',
            field=models.CharField(default=solutions.models.Question.ref, editable=False, max_length=100, unique=True),
        ),
    ]
