# Generated by Django 2.2.12 on 2020-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_auto_20200521_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscategorie',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
