# Generated by Django 2.2.12 on 2020-06-27 16:08

from django.db import migrations, models
import solutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_auto_20200627_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status_intern',
            field=models.CharField(choices=[('EA', 'Waiting'), ('RS', 'Resolved'), ('OV', 'Open'), ('FR', 'Closed'), ('RF', 'Refused'), ('AN', 'Canceled'), ('DS', 'Deactiveted')], default='OV', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='priorite',
            field=models.CharField(choices=[('F', 'Low'), ('M', 'Medium'), ('H', 'Height'), ('U', 'Urgent'), ('B', 'Bloquant')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='ref',
            field=models.PositiveIntegerField(default=solutions.models.Question.ref, verbose_name='Reference'),
        ),
    ]
