# Generated by Django 2.2.12 on 2020-06-21 11:49

from django.db import migrations, models
import solutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_auto_20200620_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponce',
            name='image',
        ),
        migrations.AddField(
            model_name='reponce',
            name='send_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='ref',
            field=models.PositiveIntegerField(default=solutions.models.Question.ref, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='reponce',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reponce',
            name='status',
            field=models.CharField(choices=[('EA', 'Waiting'), ('RS', 'Resolved'), ('FR', 'Closed'), ('RF', 'Refused')], default='EA', max_length=2),
        ),
    ]
