# Generated by Django 3.0.5 on 2020-05-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_auto_20200502_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponce',
            old_name='ticket',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='reponce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
