# Generated by Django 3.0.5 on 2020-05-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_auto_20200502_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
