# Generated by Django 2.2.12 on 2020-05-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0006_auto_20200523_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_action',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
