# Generated by Django 3.0.5 on 2020-05-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_auto_20200507_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='categorie',
            field=models.CharField(choices=[('RES', 'Network'), ('MAT', 'Hardware'), ('lOG', 'Software'), ('AUT', 'Other')], default='AUT', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='priorite',
            field=models.CharField(choices=[('F', 'Low'), ('M', 'Medium'), ('H', 'Height'), ('U', 'Urgent')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('EA', 'Waiting'), ('RS', 'Resolved'), ('OV', 'Open'), ('FR', 'Closed'), ('RF', 'refused'), ('AN', 'Canceled'), ('RP', 'Answered'), ('DS', 'Deactiveted')], default='OV', max_length=2),
        ),
    ]
