# Generated by Django 2.2.12 on 2020-05-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_question_last_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponce',
            name='status',
            field=models.CharField(choices=[('EA', 'Waiting'), ('FR', 'Closed'), ('RF', 'Refused'), ('AN', 'Canceled')], default='EA', max_length=2),
        ),
        migrations.AlterField(
            model_name='reponce',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
