# Generated by Django 2.2.12 on 2020-05-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0008_auto_20200508_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='categorie',
            field=models.CharField(choices=[('Network', (('vinyl', 'R'), ('cd', 'CD'))), ('Hardware', (('SCR', 'Ecran'), ('KBD', 'Clavier'), ('MOS', 'Souris'))), ('Software', (('OFC', 'Office'), ('EML', 'Email'))), ('Hardware', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('AUT', 'Other')], default='AUT', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('EA', 'Waiting'), ('RS', 'Resolved'), ('OV', 'Open'), ('FR', 'Closed'), ('RF', 'Refused'), ('AN', 'Canceled'), ('RP', 'Answered'), ('DS', 'Deactiveted')], default='OV', max_length=2),
        ),
    ]
