# Generated by Django 2.2.12 on 2020-06-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0009_auto_20200529_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponce',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
